### ISSUE TITLE
conda recipe?

### ISSUE THREAD

**Issue by corinwagen** [grimme-lab/CPCM-X#30]
Hey all, 

This is a fantastic paper - would love to try it out. Any potential for a conda recipe anytime soon? It'd make it a bit simpler to install in a variety of environments. Happy to help...

corin

**Comment by MtoLStoN** [comment]
Hi corin,

Thanks for the nice works. Actually, at the moment this is mostly used as a library for our ``xTB`` program and should be available in xTB 6.7.0 (which will drop in the next weeks).

However, I should definitely invest some time into adding a conda recipe for the standalone version.

**Comment by corinwagen** [comment]
Ah, sounds good - my main plan is to use with xTB anyway, although there are certainly a lot of potential standalone uses as well. Thanks for the update, and can't wait!
