### ISSUE TITLE
CMake build is missing cpcm-x-config.cmake

### ISSUE THREAD

**Issue by sheepforce** [grimme-lab/CPCM-X#31]
CPCM-X can't be found via CMake's `find_package` mechanism as `cpcm-x-config.cmake` is missing. I think this issue is identical to https://github.com/grimme-lab/numsa/issues/11.

**Comment by MtoLStoN** [comment]
Thank you. Should have been added by #32.

**Comment by sheepforce** [comment]
Thank you very much, #32 has resolved the issue. :slightly_smiling_face:
