### ISSUE TITLE
LGPL-3.0 Licensing?

### ISSUE THREAD

**Issue by TyBalduf** [grimme-lab/CPCM-X#35]
Is the long term plan to keep CPCM-X GPL-3.0 licensed? It would be nice to use in combination with xTB, but the difference in strictness of the licensing (LGPL-3.0 for xTB vs GPL-3.0 for CPCM-X) makes this tricky for certain applications.

**Comment by MtoLStoN** [comment]
Agreed, actually it seems I just made a mistake while choosing the license for the GitHub repository. It should have been a LGPL-3 license.
